name: code-coverage

# daily at 9:14 am UTC (2:14 am MT)
on: push
 

jobs:
  test-coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2


    - name: Set up node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up java (jdk-11)
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Log originating commit ID
      run: echo "full_sha1=$(git cat-file -p HEAD | grep parent | tail -1 | cut -d' ' -f2)" >> $GITHUB_ENV 
 
    - name: Install client dependencies
      run: cd Front-End && npm install

    - name: Prepare Codeclimate reporting tools
      env:
        GIT_COMMIT_SHA: ${{ env.full_sha1 }} 
        GIT_BRANCH: ${{ github.head_ref }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run client tests
      run: npm test --prefix client
      

    - name: Finish and report Codeclimate statistics
      env:
        GIT_COMMIT_SHA: ${{ env.full_sha1 }} 
        GIT_BRANCH: "main"
      run: |
        ./cc-test-reporter format-coverage -t clover target/coverage/client/clover.xml --output "codeclimate.js.json"
        ./cc-test-reporter upload-coverage --input "codeclimate.js.json"
